from solutions import *

# print("#1 Multiples of 3 or 5: " + str(multiples_of_3_or_5()))
# print("#2 Even Fibonacci Numbers : " + str(even_fibonacci_numbers()))
# print("#7 10001st Prime : " + str(prime_10001()))
# print("#12 Highly Divisible Triangular Number : " + str(highly_divisible_triangular_number()))
# print("#13 Large Sum : " + str(large_sum()))
# print("#16 Power Digit Sum : " + str(power_digit_sum()))
# print("#24 Lexicographic Permutations : " + str(lexicographic_permutations()))
# print("#26 Reciprocal Cycles : " + str(reciprocal_cycles()))
# print("#28 Number Spiral Diagonals : " + str(number_spiral_diagonals()))
# print("#42 Coded Triangle Numbers : " + str(coded_triangle_numbers()))
# print("#43 Sub-string Divisibility : " + str(sub_string_divisibility()))
# print("#45 Triangular, Pentagonal, and Hexagonal : " + str(triangular_pentagonal_and_hexagonal()))
# print("#55 Lychrel Numbers : " + str(lychrel_numbers()))
print("#81 Path Sum: Two Ways : " + str(path_sum_two_ways()))
# print("#99 Largest Exponential : " + str(largest_exponential()))
# print("#102 Triangle Containment : " + str(triangle_containment()))
# print("#205 Dice Game : " + str(dice_game()))
# print("#206 Concealed Square : " + str(concealed_square()))
